<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE vpis-response [
<!ELEMENT vpis-response (semesterjahr,query,suitabilities,staffs,locations,activities)>

<!ELEMENT semesterjahr (#PCDATA) >
<!ELEMENT query (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT hostkey (#PCDATA) >
<!ATTLIST hostkey
  semesterjahr CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA) >

<!ELEMENT staffs (staff)* >
<!ELEMENT staff (name) >
<!ATTLIST staff
  surname CDATA #REQUIRED
  forename CDATA #REQUIRED
  title1 CDATA #IMPLIED
  title2 CDATA #IMPLIED
>

<!ELEMENT locations (location)* >
<!ELEMENT location (name,hostkey,description,location-suitabilities) >
<!ATTLIST location
  size CDATA #REQUIRED
  sizeklausur CDATA #IMPLIED
>
<!ELEMENT location-suitabilities (location-suitability)* >
<!ELEMENT location-suitability (#PCDATA) >
<!ATTLIST location-suitability
  semesterjahr CDATA #REQUIRED
  primary      CDATA #IMPLIED
  secondary    CDATA #IMPLIED
>

<!ELEMENT suitabilities (suitability)* >
<!ELEMENT suitability (name,hostkey,description) >

<!ELEMENT activities (activity)* >
<!ELEMENT activity (name,hostkey,activity-type,description,activity-dates,activity-locations,activity-staffs,activity-student-sets) >
<!ATTLIST activity
  lastchange CDATA #IMPLIED
>
<!ELEMENT activity-dates (activity-date)* >
<!ELEMENT activity-date (#PCDATA) >
<!ATTLIST activity-date
  date CDATA #REQUIRED
  begin CDATA #IMPLIED
  end CDATA #IMPLIED
>
<!ELEMENT activity-type (#PCDATA) >
<!ATTLIST activity-type
  short CDATA #IMPLIED
>
<!ELEMENT activity-locations (activity-location)* >
<!ELEMENT activity-location (#PCDATA) >
<!ELEMENT activity-staffs (activity-staff)* >
<!ELEMENT activity-staff (#PCDATA) >
<!ELEMENT activity-student-sets (activity-student-set)* >
<!ELEMENT activity-student-set (#PCDATA) >


<!ENTITY Auml "&#196;" >
<!ENTITY Ouml "&#214;" >
<!ENTITY Uuml "&#220;" >
<!ENTITY auml "&#228;" >
<!ENTITY ouml "&#246;" >
<!ENTITY uuml "&#252;" >
<!ENTITY szlig "&#223;" >
<!ENTITY eacute "&#233;" >
]>

<!--Template veranstaltungen.2009-01.tpl.xml -->
<vpis-response>
 <semesterjahr>SS2021</semesterjahr>
 <query>Raum:Uebersicht:Iserlohn:2021-04-30</query>

 <suitabilities>
  <suitability>
   <name>R#Is Tutorien</name>
   <hostkey semesterjahr="SS2021">#SPLUS105BC3</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Iserlohn VS VAI</name>
   <hostkey semesterjahr="SS2021">#SPLUS5B7EDC</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is PC-Pools</name>
   <hostkey semesterjahr="SS2021">#SPLUS5F1FDA</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is PC-Pools 2,4,14</name>
   <hostkey semesterjahr="SS2021">#SPLUS815ABD</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is</name>
   <hostkey semesterjahr="SS2021">#SPLUS9E087E</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is mit Beamer</name>
   <hostkey semesterjahr="SS2021">#SPLUSC166B0</hostkey>
   <description>R&auml;ume mit Beamer</description>
  </suitability>
  <suitability>
   <name>R#Is mit Whiteboard</name>
   <hostkey semesterjahr="SS2021">#SPLUSC166B1</hostkey>
   <description>R&auml;ume mit Whiteboard</description>
  </suitability>
  <suitability>
   <name>R#Is mit Mikrofon</name>
   <hostkey semesterjahr="SS2021">#SPLUS24E446</hostkey>
   <description>R&auml;ume mit Mikrofon</description>
  </suitability>
  <suitability>
   <name>R#Is Vorlesungsr&auml;ume</name>
   <hostkey semesterjahr="SS2021">#SPLUS5F1FD1</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is Vorl. (gro&szlig;)</name>
   <hostkey semesterjahr="SS2021">#SPLUSB0205E</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is mit Tafel</name>
   <hostkey semesterjahr="SS2021">#SPLUSC166B2</hostkey>
   <description>R&auml;ume mit Kreidetafel</description>
  </suitability>
  <suitability>
   <name>R#Is Vorl. (klein)</name>
   <hostkey semesterjahr="SS2021">#SPLUSD2E253</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is Laboratorien FB I+N</name>
   <hostkey semesterjahr="SS2021">#SPLUSC166AE</hostkey>
   <description>Laboratorien des Fachbereichs Informatik und Naturwissenschaften</description>
  </suitability>
  <suitability>
   <name>R#Is PC-Pool 8,9,12</name>
   <hostkey semesterjahr="SS2021">#SPLUSC46FE6</hostkey>
   <description></description>
  </suitability>
  <suitability>
   <name>R#Is AI Poolr&auml;ume FB I+N</name>
   <hostkey semesterjahr="SS2021">#SPLUS25B42B</hostkey>
   <description>Poolr&auml;ume des Fachbereichs Informatik und Naturwissenschaften</description>
  </suitability>
 </suitabilities>
 <staffs>
<staff><name>#SPLUS8D4852</name></staff>
  <staff surname="Borchert" forename="Thomas" title1="Dr." title2="Prof.">
   <name>Borchert</name>
  </staff>
  <staff surname="Buschmann" forename="Ralf" title1="Dipl.-Ing." title2="">
   <name>Buschmann</name>
  </staff>
  <staff surname="Cordes" forename="Susanne" title1="Dr.-Ing." title2="Prof.">
   <name>Cordes, Su.</name>
  </staff>
  <staff surname="Dahmen" forename="Claudio" title1="Dr." title2="Prof.">
   <name>Dahmen</name>
  </staff>
  <staff surname="Dr&ouml;lle" forename="Oliver" title1="Dipl.-Ing." title2="">
   <name>Dr&ouml;lle</name>
  </staff>
  <staff surname="Ellermeyer" forename="Tobias" title1="Dr.-Ing." title2="Prof.">
   <name>Ellermeyer</name>
  </staff>
  <staff surname="Faulstich" forename=" Matthias" title1=" Dipl. Ing." title2="">
   <name>Faulstich</name>
  </staff>
  <staff surname="Feser" forename=" Ralf" title1=" Dr.-Ing." title2=" Prof.">
   <name>Feser</name>
  </staff>
  <staff surname="Frieling" forename="Melanie" title1="Dipl.-Ing.M" title2="">
   <name>Frieling</name>
  </staff>
  <staff surname="Gawron" forename="Christian" title1="Dr." title2="Prof.">
   <name>Gawron, C.</name>
  </staff>
  <staff surname="Gerhardt" forename=" J&uuml;rgen" title1=" Dr. rer. pol." title2=" Prof.">
   <name>Gerhardt</name>
  </staff>
  <staff surname="Gerles" forename="Ren&eacute;" title1="B.Sc." title2="">
   <name>Gerles, R.</name>
  </staff>
  <staff surname="Gie&szlig;" forename="Michael" title1="Dr." title2="">
   <name>Gie&szlig;</name>
  </staff>
  <staff surname="Gogolin" forename="Uwe" title1="Dipl.-Inform. (FH)" title2="">
   <name>Gogolin</name>
  </staff>
  <staff surname="Hannibal" forename="Wilhelm" title1="Prof. Dr.-Ing." title2="">
   <name>Hannibal</name>
  </staff>
  <staff surname="Holke" forename="Tobias" title1="M.Sc." title2="">
   <name>Holke, T.</name>
  </staff>
  <staff surname="H&uuml;hne" forename="Rylee" title1="Dr." title2="Prof.">
   <name>H&uuml;hne</name>
  </staff>
  <staff surname="Lenninghaus" forename="Nina" title1="" title2="">
   <name>Lenninghaus</name>
  </staff>
  <staff surname="Meisterjahn" forename=" Peter" title1=" Dr. rer. nat." title2=" Prof.">
   <name>Meisterjahn</name>
  </staff>
  <staff surname="Menze" forename="Wolfgang" title1="" title2="">
   <name>Menze</name>
  </staff>
  <staff surname="M&uuml;tterlein" forename=" Bernward" title1=" Dr.-Ing." title2=" Prof.">
   <name>M&uuml;tterlein</name>
  </staff>
  <staff surname="Nawrath" forename="Niklas" title1="M.Sc." title2="">
   <name>Nawrath, N.</name>
  </staff>
  <staff surname="Otto" forename="Robin" title1="M.Eng." title2="">
   <name>Otto</name>
  </staff>
  <staff surname="Perlick" forename="Olaf" title1="Dipl.Inform." title2="">
   <name>Perlick, O.</name>
  </staff>
  <staff surname="Rapp" forename="Sebastian" title1="B.Sc." title2="">
   <name>Rapp, S.</name>
  </staff>
  <staff surname="Roloff" forename=" Christian" title1=" Dipl.-Ing." title2="">
   <name>Roloff</name>
  </staff>
  <staff surname="R&uuml;bsam" forename="Michael" title1="Dr." title2="Prof.">
   <name>R&uuml;bsam</name>
  </staff>
  <staff surname="Schmidt" forename="Sebastian" title1="B.Sc." title2="">
   <name>Schmidt, S.2</name>
  </staff>
  <staff surname="Schulte" forename="Moritz" title1="M.Sc." title2="">
   <name>Schulte, Mo.</name>
  </staff>
  <staff surname="Sch&uuml;tte" forename="Sebastian" title1="M.Eng." title2="">
   <name>Sch&uuml;tte, S.</name>
  </staff>
  <staff surname="Skambraks" forename="Martin" title1="Dr.-Ing." title2="Prof.">
   <name>Skambraks</name>
  </staff>
  <staff surname="Tigges" forename="J&ouml;rg" title1="B.Eng." title2="">
   <name>Tigges</name>
  </staff>
  <staff surname="Ujma" forename="Andreas" title1="Dr.-Ing." title2="Prof.">
   <name>Ujma</name>
  </staff>
  <staff surname="vom Orde" forename="Philipp" title1="M.Sc." title2="">
   <name>vom Orde, P.</name>
  </staff>
 </staffs>

 <locations>
  <location size="30" sizeklausur="12">
   <name>Is-A.EG06</name>
   <hostkey semesterjahr="SS2021">#SPLUS7101D1</hostkey>
   <description>H&ouml;rsaal mit 30 Pl&auml;tzen</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS5F1FD1</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B2</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSD2E253</location-suitability>
   </location-suitabilities>
  </location>
  <location size="17" sizeklausur="0">
   <name>Is-A.EG11</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E8E</hostkey>
   <description>PC-Poolraum</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="16" sizeklausur="0">
   <name>Is-A.UG-Halle-1</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E90</hostkey>
   <description>Labor Nevoigt</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="16" sizeklausur="0">
   <name>Is-A.UG-Halle-2</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E91</hostkey>
   <description>Labor Hannibal</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="16" sizeklausur="0">
   <name>Is-A.UG-Halle-3</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E92</hostkey>
   <description>Getriebetechnik Sch&ouml;ler</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="16" sizeklausur="0">
   <name>Is-A.UG04</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E8F</hostkey>
   <description>Leistungspr&uuml;fstand 2</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="16" sizeklausur="0">
   <name>Is-A.UG08</name>
   <hostkey semesterjahr="SS2021">#SPLUS3F5E93</hostkey>
   <description>Allradpr&uuml;fstand</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="378" sizeklausur="101">
   <name>Is-Audimax</name>
   <hostkey semesterjahr="SS2021">#LOCISAMX000</hostkey>
   <description>Dr.-Ing. Jochen F. Kirchhoff-H&ouml;rsaal</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS24E446</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS5F1FD1</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSB0205E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B2</location-suitability>
   </location-suitabilities>
  </location>
  <location size="15" sizeklausur="0">
   <name>Is-C102</name>
   <hostkey semesterjahr="SS2021">#SPLUSCD2392</hostkey>
   <description></description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="15" sizeklausur="0">
   <name>Is-C103</name>
   <hostkey semesterjahr="SS2021">#SPLUS38CC5F</hostkey>
   <description></description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="5" sizeklausur="0">
   <name>Is-C203</name>
   <hostkey semesterjahr="SS2021">#LOCISC02030</hostkey>
   <description>B&uuml;ro Prof. Fobbe</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="14" sizeklausur="0">
   <name>Is-C204</name>
   <hostkey semesterjahr="SS2021">#LOCISC02040</hostkey>
   <description>Organische Chemie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="14" sizeklausur="0">
   <name>Is-C206</name>
   <hostkey semesterjahr="SS2021">#LOCISC02060</hostkey>
   <description>Physikalische Chemie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="5" sizeklausur="0">
   <name>Is-C207</name>
   <hostkey semesterjahr="SS2021">#LOCISC02070</hostkey>
   <description>B&uuml;ro Roloff</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="115" sizeklausur="16">
   <name>Is-C301</name>
   <hostkey semesterjahr="SS2021">#LOCISC03010</hostkey>
   <description>H&ouml;rsaal  C-Geb&auml;ude 115 Pl&auml;tze</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS24E446</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS5F1FD1</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSB0205E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B2</location-suitability>
   </location-suitabilities>
  </location>
  <location size="12" sizeklausur="0">
   <name>Is-C304</name>
   <hostkey semesterjahr="SS2021">#LOCISC03040</hostkey>
   <description>D&uuml;nnschichtlabor ; Organische Chemie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="5" sizeklausur="0">
   <name>Is-C305</name>
   <hostkey semesterjahr="SS2021">#LOCISC03050</hostkey>
   <description>B&uuml;ro Rudolf</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="12" sizeklausur="0">
   <name>Is-C307</name>
   <hostkey semesterjahr="SS2021">#LOCISC03070</hostkey>
   <description>Lacklabor; Organische Schichten</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-C308</name>
   <hostkey semesterjahr="SS2021">#LOCISC03080</hostkey>
   <description>Ex Bio</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-C309</name>
   <hostkey semesterjahr="SS2021">#LOCISC03090</hostkey>
   <description>Labor f&uuml;r Chemische Nanotechnologie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-C310</name>
   <hostkey semesterjahr="SS2021">#LOCISC03100</hostkey>
   <description>Labor f&uuml;r Nanotechnologie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="5" sizeklausur="0">
   <name>Is-C311</name>
   <hostkey semesterjahr="SS2021">#LOCISC03110</hostkey>
   <description>Chemisches Mess- und Pr&uuml;flabor 1</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="5" sizeklausur="0">
   <name>Is-C312</name>
   <hostkey semesterjahr="SS2021">#LOCISC03120</hostkey>
   <description>Chemisches Mess- und Pr&uuml;flabor 2</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-H101</name>
   <hostkey semesterjahr="SS2021">#LOCISH01010</hostkey>
   <description>Besprechungsraum per Tel. 111 buchen</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS23F7AB</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="1">
   <name>Is-H103</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835BF</hostkey>
   <description>Prof. Fiolka</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H104</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C0</hostkey>
   <description>Prof. Gruber</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H105</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C6</hostkey>
   <description>Dekanat M</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H106</name>
   <hostkey semesterjahr="SS2021">#LOCISH01060</hostkey>
   <description>Sekretariat Dekanat M &amp; I+N</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H107</name>
   <hostkey semesterjahr="SS2021">#LOCISH01070</hostkey>
   <description>Dekanat I+N; Erlemann</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H108</name>
   <hostkey semesterjahr="SS2021">#SPLUS24E457</hostkey>
   <description>Sekretariat Vomhof</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H109</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C1</hostkey>
   <description>B&uuml;ro</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H110</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C3</hostkey>
   <description>B&uuml;ro Drees</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="12" sizeklausur="0">
   <name>Is-H112</name>
   <hostkey semesterjahr="SS2021">#SPLUSCB1824</hostkey>
   <description>PPS - ERP Labor</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="4" sizeklausur="0">
   <name>Is-H113</name>
   <hostkey semesterjahr="SS2021">#LOCISH01130</hostkey>
   <description>Studierenden-Serviceb&uuml;ro; Blanck, Khongklad, Obst, Przibylla</description>
   <location-suitabilities>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H115</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C5</hostkey>
   <description>B&uuml;ro Grote</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="1" sizeklausur="0">
   <name>Is-H119</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C4</hostkey>
   <description>B&uuml;ro Witt</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="15" sizeklausur="4">
   <name>Is-H201</name>
   <hostkey semesterjahr="SS2021">#SPLUSFA1DA6</hostkey>
   <description>Digitaltechnik-Labor</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
   </location-suitabilities>
  </location>
  <location size="48" sizeklausur="14">
   <name>Is-H205</name>
   <hostkey semesterjahr="SS2021">#SPLUS38CC42</hostkey>
   <description>H&ouml;rsaal mit Beamer 48 Pl&auml;tze</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS5F1FD1</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B2</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSD2E253</location-suitability>
   </location-suitabilities>
  </location>
  <location size="24" sizeklausur="14">
   <name>Is-H206</name>
   <hostkey semesterjahr="SS2021">#SPLUS38CC41</hostkey>
   <description>H&ouml;rsaal mit Beamer 24 Pl&auml;tze</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS5F1FD1</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B0</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUSC166B2</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSD2E253</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-H208</name>
   <hostkey semesterjahr="SS2021">#SPLUSE0B62B</hostkey>
   <description>Labor f&uuml;r Biotechnologie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-H209</name>
   <hostkey semesterjahr="SS2021">#SPLUS24E44A</hostkey>
   <description>Labor f&uuml;r Biotechnologie / Zellbiologie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="10" sizeklausur="0">
   <name>Is-H210</name>
   <hostkey semesterjahr="SS2021">#SPLUS38CC4C</hostkey>
   <description>Labor f&uuml;r Biotechnologie</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AE</location-suitability>
   </location-suitabilities>
  </location>
  <location size="3" sizeklausur="0">
   <name>Is-H210a</name>
   <hostkey semesterjahr="SS2021">#SPLUS8835C8</hostkey>
   <description>B&uuml;ro Kumpf</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="3" sizeklausur="0">
   <name>Is-H211</name>
   <hostkey semesterjahr="SS2021">#SPLUSC4C9CC</hostkey>
   <description>B&uuml;ro Prof. Eisenbarth</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUS9E087E</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="J" secondary="N">#SPLUSC166AF</location-suitability>
   </location-suitabilities>
  </location>
  <location size="48" sizeklausur="13">
   <name>Is-H212</name>
   <hostkey semesterjahr="SS2021">#SPLUS38CC40</hostkey>
   <description>H&ouml;rsaal mit Beamer 48 Pl&auml;tze</description>
   <location-suitabilities>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS105BC3</location-suitability>
     <location-suitability semesterjahr="SS2021" primary="N" secondary="J">#SPLUS5F1FD1</location-suitability>